# Generated by Django 4.2.1 on 2023-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_options_alter_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="common_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Preferred Name"
            ),
        ),
    ]
