# Generated by Django 4.2.1 on 2023-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_student_common_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.IntegerField(
                choices=[
                    (1, "First Year"),
                    (2, "Second Year"),
                    (3, "Third Year"),
                    (4, "Fourth Year"),
                    (5, "Fifth Year"),
                    (6, "Sixth Year"),
                    (7, "Seventh Year"),
                ],
                default=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="common_name",
            field=models.CharField(max_length=255, verbose_name="Preferred Name"),
        ),
    ]
