# Generated by Django 4.2.1 on 2023-05-15 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_student_year_alter_student_common_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.IntegerField(
                choices=[
                    (1, "First"),
                    (2, "Second"),
                    (3, "Third"),
                    (4, "Fourth"),
                    (5, "Fifth"),
                    (6, "Sixth"),
                    (7, "Seventh"),
                ],
                validators=[
                    django.core.validators.MaxValueValidator(7),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
