# Generated by Django 4.2.1 on 2023-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_student_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uid",
            field=models.CharField(blank=True, max_length=20, verbose_name="User ID"),
        ),
    ]
