# Generated by Django 4.2.1 on 2023-05-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="common_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="common_name",
            field=models.CharField(
                default="<function now at 0x0000026D5153E5C0>",
                max_length=255,
                verbose_name="Preferred Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                default="<function now at 0x0000026D5153E5C0>",
                max_length=255,
                verbose_name="First Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                default="<function now at 0x0000026D5153E5C0>",
                max_length=255,
                verbose_name="Last Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Middle Name"
            ),
        ),
    ]
