# Generated by Django 4.2.1 on 2023-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_student_common_name_remove_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="employee_type",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
