# Generated by Django 4.2.1 on 2023-05-17 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_student_employee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="house",
            field=models.CharField(
                choices=[
                    ("GR", "Gryffindor"),
                    ("HU", "Huffelpuff"),
                    ("RA", "Ravenclaw"),
                    ("SL", "Slytherin"),
                    ("UN", "Unsorted"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.IntegerField(
                choices=[
                    (-1, "Unknown"),
                    (1, "First"),
                    (2, "Second"),
                    (3, "Third"),
                    (4, "Fourth"),
                    (5, "Fifth"),
                    (6, "Sixth"),
                    (7, "Seventh"),
                ],
                validators=[
                    django.core.validators.MaxValueValidator(7),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
