# Generated by Django 4.2.1 on 2023-05-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_student_house_alter_student_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                default="Unknown", max_length=20, verbose_name="Title"
            ),
        ),
    ]
