# Generated by Django 4.2.1 on 2023-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_customuser_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                choices=[
                    ("Mr", "Mr"),
                    ("Master", "Master"),
                    ("Mrs", "Mrs"),
                    ("Ms", "Ms"),
                    ("Miss", "Miss"),
                    ("Mx", "Mx"),
                    ("Madam", "Madam"),
                    ("Madame", "Madame"),
                    ("Dr", "Dr"),
                    ("Professor", "Professor"),
                    ("Minister", "Minister"),
                    ("Sir", "Sir"),
                    ("Dame", "Dame"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Title",
            ),
        ),
    ]
