# Generated by Django 4.2.1 on 2023-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_customuser_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                choices=[
                    ("Miss", "Miss"),
                    ("Mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("Ms", "Ms"),
                    ("Mx", "Mx"),
                    ("Doctor", "Dr"),
                    ("Madam", "Madam"),
                    ("Madame", "Madame"),
                    ("Master", "Master"),
                    ("Professor", "Professor"),
                    ("Minister", "Minister"),
                    ("Sir", "Sir"),
                    ("Dame", "Dame"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="house",
            field=models.CharField(
                choices=[
                    ("GR", "Gryffindor"),
                    ("HU", "Hufflepuff"),
                    ("RA", "Ravenclaw"),
                    ("SL", "Slytherin"),
                    ("UN", "Unknown"),
                ],
                default="UN",
                max_length=2,
            ),
        ),
    ]
