# Generated by Django 4.2.1 on 2023-05-21 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_customuser_title_alter_student_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuidditchPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_player",
                    models.BooleanField(default=False, verbose_name="Is Player"),
                ),
                (
                    "team_member_type",
                    models.TextField(
                        choices=[("ME", "Team Member"), ("RE", "Team Reserve")],
                        max_length=2,
                    ),
                ),
                (
                    "team_position",
                    models.TextField(
                        choices=[
                            ("KE", "Keeper"),
                            ("CH", "Chaser"),
                            ("BE", "Beater"),
                            ("SE", "Seeker"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
