# Generated by Django 4.2.1 on 2023-05-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_quidditchplayer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quidditchplayer",
            options={
                "verbose_name": "Quidditch Player",
                "verbose_name_plural": "Quidditch Players",
            },
        ),
        migrations.AlterField(
            model_name="quidditchplayer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
    ]
