# Generated by Django 4.2.1 on 2023-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_quidditchplayer_is_captain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quidditchplayer",
            old_name="user",
            new_name="student",
        ),
    ]
