# Generated by Django 4.2.1 on 2023-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_quidditchplayer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quidditchplayer",
            options={
                "ordering": ["student__house", "student__user__last_name"],
                "verbose_name": "Quidditch Player",
                "verbose_name_plural": "Quidditch Players",
            },
        ),
        migrations.AddField(
            model_name="quidditchplayer",
            name="is_suspended",
            field=models.BooleanField(default=False, verbose_name="Is Suspended"),
        ),
    ]
