# Generated by Django 4.2.1 on 2023-05-31 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sex",
            field=models.CharField(
                choices=[("U", "Unknown"), ("M", "Male"), ("F", "Female")],
                default="U",
                max_length=1,
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Miss", "Miss"),
                    ("Mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("Ms", "Ms"),
                    ("Mx", "Mx"),
                    ("Doctor", "Dr"),
                    ("Madam", "Madam"),
                    ("Madame", "Madame"),
                    ("Master", "Master"),
                    ("Professor", "Professor"),
                    ("Minister", "Minister"),
                    ("Sir", "Sir"),
                    ("Dame", "Dame"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
