# Generated by Django 4.2.1 on 2023-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_staff_options_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="children",
        ),
        migrations.AddField(
            model_name="parent",
            name="children",
            field=models.ManyToManyField(to="users.student"),
        ),
    ]
