# Generated by Django 4.2.1 on 2023-06-01 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_remove_parent_children_parent_children"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quidditchplayer",
            options={
                "ordering": [
                    "student__house",
                    "student__user__last_name",
                    "student__user__first_name",
                ],
                "verbose_name": "Quidditch Player",
                "verbose_name_plural": "Quidditch Players",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ("user__last_name",),
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AddField(
            model_name="parent",
            name="linked_to_other_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.parent",
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
