# Generated by Django 4.2.1 on 2023-06-01 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_alter_parent_linked_to_other_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="linked_to_other_parent",
        ),
    ]
