# Generated by Django 4.2.1 on 2023-06-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_parent_related_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="related_parent",
            field=models.ManyToManyField(
                blank=True, default=None, max_length=5, to="users.parent"
            ),
        ),
    ]
