# Generated by Django 4.2.1 on 2023-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_alter_parent_related_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="prefect",
            field=models.BooleanField(default=False, verbose_name="Is Prefect"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="related_parent",
            field=models.ManyToManyField(
                blank=True, default=None, max_length=1, to="users.parent"
            ),
        ),
    ]
