# Generated by Django 4.2.1 on 2023-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_student_prefect_alter_parent_related_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_head_of_house",
            field=models.BooleanField(default=False, verbose_name="Is Head of House"),
        ),
    ]
