# Generated by Django 4.2.1 on 2023-06-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_staff_is_head_of_house"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parent",
            options={"verbose_name": "Parent", "verbose_name_plural": "Parents"},
        ),
        migrations.AlterField(
            model_name="parent",
            name="children",
            field=models.ManyToManyField(to="users.student", verbose_name="Children"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="related_parent",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                max_length=1,
                related_name="parent_of",
                to="users.parent",
            ),
        ),
    ]
