# Generated by Django 4.2.1 on 2023-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0034_alter_parent_options_alter_parent_children_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="children",
            field=models.ManyToManyField(
                related_name="children_of", to="users.student", verbose_name="Children"
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="related_parent",
            field=models.ManyToManyField(blank=True, default=None, to="users.parent"),
        ),
    ]
