# Generated by Django 4.2.1 on 2023-07-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="House Name"
                    ),
                ),
                (
                    "mascot",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="House Mascot"
                    ),
                ),
                (
                    "ghost",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="House Ghost",
                    ),
                ),
                (
                    "crest",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="House Crest"
                    ),
                ),
                (
                    "head_of_house",
                    models.ForeignKey(
                        limit_choices_to={"staff_type": "AC"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.staff",
                        verbose_name="Professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "School House",
                "verbose_name_plural": "School Houses",
                "ordering": ["name"],
            },
        ),
    ]
