# Generated by Django 4.2.1 on 2023-07-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_schoolhouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="test_house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.schoolhouse",
            ),
        ),
    ]
