# Generated by Django 4.2.5 on 2023-09-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0041_staff_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created_externally",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Created From LDAP"
            ),
        ),
    ]
