# Generated by Django 4.2.5 on 2023-09-21 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_customuser_created_externally"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="house",
            field=models.CharField(
                choices=[
                    ("GR", "Gryffindor"),
                    ("HU", "Hufflepuff"),
                    ("RA", "Ravenclaw"),
                    ("SL", "Slytherin"),
                    ("UN", "Unknown"),
                ],
                default="UN",
                max_length=2,
                verbose_name="House",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "First"),
                    (2, "Second"),
                    (3, "Third"),
                    (4, "Fourth"),
                    (5, "Fifth"),
                    (6, "Sixth"),
                    (7, "Seventh"),
                ],
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(7),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Year",
            ),
        ),
    ]
