# Generated by Django 4.2.5 on 2023-09-21 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_alter_student_house_alter_student_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Joined"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Last Logged In"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="uid",
            field=models.CharField(max_length=20, unique=True, verbose_name="Username"),
        ),
    ]
