# Generated by Django 4.2.1 on 2023-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        max_length=2500, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "course_code",
                    models.CharField(max_length=10, verbose_name="Course Code"),
                ),
            ],
            options={
                "verbose_name": "Basic Course",
                "verbose_name_plural": "Basic Courses",
                "ordering": ["name"],
            },
        ),
    ]
