# Generated by Django 4.2.1 on 2023-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Course Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Course Code"
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("OWL", "OWL"),
                            ("NEWT", "NEWT"),
                            ("SPECIAL", "Specialised Subject"),
                        ],
                        default="OWL",
                        max_length=7,
                        verbose_name="Course Type",
                    ),
                ),
                (
                    "required",
                    models.CharField(
                        blank=True,
                        choices=[("R", "Required"), ("E", "Elective")],
                        max_length=1,
                        verbose_name="Course Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basic Course",
                "verbose_name_plural": "Basic Courses",
                "ordering": ["course_code"],
            },
        ),
    ]
