# Generated by Django 4.2.1 on 2023-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basiccourse",
            name="course_code",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Course Code"
            ),
        ),
        migrations.AlterField(
            model_name="basiccourse",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
