# Generated by Django 4.2.1 on 2023-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_basiccourse_course_code_alter_basiccourse_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basiccourse",
            name="description",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Description"
            ),
        ),
    ]
