# Generated by Django 4.2.1 on 2023-06-05 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_schoolyear_name_alter_schoolyear_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolyear",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 5, 15, 2, 29, 466201, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
