# Generated by Django 4.2.1 on 2023-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_alter_schoolyear_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolyear",
            name="end_year",
            field=models.BigIntegerField(
                default=2022, editable=False, verbose_name="End Year"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolyear",
            name="start_year",
            field=models.BigIntegerField(
                default=2023, editable=False, verbose_name="Start Year"
            ),
            preserve_default=False,
        ),
    ]
