# Generated by Django 4.2.1 on 2023-06-05 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_schoolyear_end_year_schoolyear_start_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolyear",
            options={
                "verbose_name": "School Year",
                "verbose_name_plural": "School Years",
            },
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="end_year",
            field=models.BigIntegerField(
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(2020),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="End Year",
            ),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="start_year",
            field=models.BigIntegerField(
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(2020),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="Start Year",
            ),
        ),
    ]
