# Generated by Django 4.2.1 on 2023-06-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_alter_customuser_is_staff"),
        ("school", "0012_basiccourse_owner_alter_basicclass_school_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basiccourse",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.staff",
            ),
        ),
    ]
