# Generated by Django 4.2.1 on 2023-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_alter_customuser_is_staff"),
        ("school", "0013_alter_basiccourse_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basiccourse",
            options={
                "ordering": ["course_code"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AddField(
            model_name="basicclass",
            name="student",
            field=models.ManyToManyField(to="users.student", verbose_name="student"),
        ),
        migrations.AddField(
            model_name="basicclass",
            name="teacher",
            field=models.ManyToManyField(
                limit_choices_to={"staff_type": "AC"},
                to="users.staff",
                verbose_name="Professor",
            ),
        ),
    ]
