# Generated by Django 4.2.1 on 2023-06-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0014_alter_basiccourse_options_basicclass_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basiccourse",
            name="description",
            field=models.CharField(
                blank=True, max_length=2500, null=True, verbose_name="Description"
            ),
        ),
    ]
