# Generated by Django 4.2.1 on 2023-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0015_alter_basiccourse_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicclass",
            name="class_code",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                max_length=20,
                null=True,
                verbose_name="Class Code",
            ),
        ),
    ]
