# Generated by Django 4.2.1 on 2023-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0016_basicclass_class_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicclass",
            name="class_code",
            field=models.CharField(
                blank=True,
                default="0001",
                editable=False,
                max_length=20,
                null=True,
                verbose_name="Class Code",
            ),
        ),
    ]
