# Generated by Django 4.2.1 on 2023-06-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0018_alter_basiccourse_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="basicclass",
            constraint=models.UniqueConstraint(
                fields=("name", "course"),
                name="name_course",
                violation_error_message="Error",
            ),
        ),
    ]
