# Generated by Django 4.2.1 on 2023-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0019_basicclass_name_course"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="basicclass",
            name="name_course",
        ),
        migrations.AddConstraint(
            model_name="basicclass",
            constraint=models.UniqueConstraint(
                fields=("school_year", "course"),
                name="name_course",
                violation_error_message="Error",
            ),
        ),
    ]
