# Generated by Django 4.2.1 on 2023-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0021_remove_basicclass_name_course_basicclass_name_course"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="basicclass",
            name="name_course",
        ),
        migrations.AlterField(
            model_name="basicclass",
            name="class_code",
            field=models.CharField(
                blank=True,
                default="0001",
                editable=False,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Class Code",
            ),
        ),
        migrations.AddConstraint(
            model_name="basicclass",
            constraint=models.UniqueConstraint(
                fields=("name", "course"), name="name_course"
            ),
        ),
    ]
