# Generated by Django 4.2.1 on 2023-06-06 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0022_remove_basicclass_name_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basicclass",
            options={
                "ordering": ["name"],
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolyear",
            options={
                "ordering": ["name"],
                "verbose_name": "School Year",
                "verbose_name_plural": "School Years",
            },
        ),
    ]
