# Generated by Django 4.2.1 on 2023-06-06 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0023_alter_basicclass_options_alter_schoolyear_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolyear",
            options={
                "verbose_name": "School Year",
                "verbose_name_plural": "School Years",
            },
        ),
    ]
