# Generated by Django 4.2.1 on 2023-06-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_alter_customuser_is_staff"),
        ("school", "0025_alter_basicclass_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicclass",
            name="student",
            field=models.ManyToManyField(
                blank=True, to="users.student", verbose_name="student"
            ),
        ),
    ]
