# Generated by Django 4.2.1 on 2023-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0026_alter_basicclass_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="basiccourse",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
