# Generated by Django 4.2.1 on 2023-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0029_alter_basiccourse_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basiccourse",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("OWL", "OWL"),
                    ("NEWT", "NEWT"),
                    ("SPECIAL", "Specialised Subject"),
                    ("EXTERNAL", "External Course"),
                ],
                default="OWL",
                max_length=8,
                verbose_name="Course Type",
            ),
        ),
    ]
