# Generated by Django 4.2.1 on 2023-07-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0030_alter_basiccourse_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicclass",
            name="slug",
            field=models.SlugField(null=False,unique=True),
        ),
    ]
