# Generated by Django 4.2.1 on 2023-07-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0033_alter_basicclass_class_code_alter_basicclass_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolyear",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
