# Generated by Django 4.2.1 on 2023-07-11 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0035_alter_schoolyear_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolyear",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
