# Generated by Django 4.2.1 on 2023-07-25 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0037_house"),
    ]

    operations = [
        migrations.DeleteModel(
            name="House",
        ),
    ]
