# Generated by Django 4.2.1 on 2023-07-30 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0038_delete_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicclass",
            name="max_num_students",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
