# Generated by Django 4.2.1 on 2023-08-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0041_enrolment_alter_basicclass_student"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="enrolment",
            constraint=models.UniqueConstraint(
                fields=("student", "basic_class"), name="unique_student_class"
            ),
        ),
    ]
