# Generated by Django 4.2.1 on 2023-08-04 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0043_coursecategory_alter_enrolment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="basiccourse",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.coursecategory",
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9\\s]*$", "Alphanumeric characters only"
                    ),
                ],
                verbose_name="Category Name",
            ),
        ),
    ]
