# Generated by Django 4.2.1 on 2023-08-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0044_basiccourse_category_alter_coursecategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basiccourse",
            name="category",
        ),
        migrations.AddField(
            model_name="basiccourse",
            name="Course Category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.coursecategory",
            ),
        ),
        migrations.AlterField(
            model_name="basiccourse",
            name="required",
            field=models.CharField(
                blank=True,
                choices=[("R", "Required"), ("E", "Elective")],
                max_length=1,
                verbose_name="Course Curriculum",
            ),
        ),
    ]
