# Generated by Django 4.2.1 on 2023-08-04 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0045_remove_basiccourse_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basiccourse",
            old_name="Course Category",
            new_name="category",
        ),
    ]
