# Generated by Django 4.2.1 on 2023-08-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0047_alter_basiccourse_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="student_class_status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("E", "Expired"),
                    ("N", "Not Eligible"),
                    ("P", "Pending"),
                    ("S", "Suspended"),
                ],
                default="A",
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
