# Generated by Django 4.2.1 on 2023-08-16 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_author_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowerfine",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="borrowerfine",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Available"),
                    ("l", "Lost"),
                    ("m", "Maintenance"),
                    ("o", "On loan"),
                    ("r", "Reserved"),
                ],
                default="m",
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
