# Generated by Django 4.2.1 on 2023-08-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0007_borrowerfine_created_date_borrowerfine_modified_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowerfine",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.bookinstance",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="borrowerfine",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.borrower"
            ),
        ),
        migrations.AlterField(
            model_name="borrowerfine",
            name="fine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="catalog.fine"
            ),
        ),
    ]
