# Generated by Django 4.2.1 on 2023-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_borrowerfine_item_alter_borrowerfine_borrower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowerfine",
            name="status",
            field=models.CharField(
                choices=[("O", "Outstanding"), ("P", "Paid")],
                default="O",
                max_length=11,
                verbose_name="Fine Status",
            ),
        ),
    ]
