# Generated by Django 4.2.1 on 2023-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_borrowerfine_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowerfine",
            name="resolved_date",
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
